config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :votes
  root 'static_pages#home'
  get  '/help', to: 'static_pages#help'
  get  '/signup', to: 'users#new'
end

app/models/application_record.rb
# frozen_string_literal: true

# Base model definition
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
end

app/models/vote.rb
# frozen_string_literal: true

class Vote < ApplicationRecord
  validates :title, :deadline, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

# Static Pages' controller
class StaticPagesController < ApplicationController
  def home; end

  def help
    render :help
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new; end
end

app/controllers/votes_controller.rb
# frozen_string_literal: true

class VotesController < ApplicationController
  before_action :set_vote, only: %i[show edit update destroy]

  def index
    @votes = Vote.all
    # TODO: ユーザーモデルを作成したら、そのユーザーが参加する、またはそのユーザーの作成したVoteのみを降順に取得
  end

  def new
    @vote = Vote.new
  end

  def create
    @vote = Vote.new(vote_params)
    if @vote.save
      redirect_to votes_path, notice: 'Vote was successfully created.'
    else
      render :new
    end
  end

  def show
    render :show
  end

  def edit
    render :edit
  end

  def update
    if @vote.update(vote_params)
      redirect_to votes_path, notice: 'Vote was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    if @vote.destroy
      redirect_to votes_path, alert: 'Vote was deleted.'
    else
      redirect_to votes_path, alert: 'Delete is unsuccessfull.'
    end
  end

  private

  def set_vote
    @vote = Vote.find(params[:id])
  end

  def vote_params
    params.require(:vote).permit(:title, :deadline)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Pollman'
    if page_title.empty?
      base_title
    else
      "#{page_title}|#{base_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
# frozen_string_literal: true

# Static Pages' helper methods
module StaticPagesHelper
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/helpers/votes_helper.rb
# frozen_string_literal: true

module VotesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
    <div class="container">
        <%= link_to 'Poll', root_path, id: 'logo' %>
        <nav>
            <ul class='nav navbar-nav navbar-right'>
                <li><%= link_to "Home", root_path %></li>
                <li><%= link_to "Help", help_path %></li>
                <li><%= link_to "Votes", votes_path %></li>
                <li><%= link_to "Log in", "#" %></li>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>What's Pollman</h1>

app/views/static_pages/home.html.erb
<% provide(:title) %>
<div class="center jumbotron">
  <h1>Welcome to Pollman</h1>

  <h2>Join us and Poll it.</h2>
  <p>If you want to make some poll among your community, Pollman helps you!</p>
  <%= link_to "Sign up and poll", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<p>This will be a signup page for new users.</p>

app/views/votes/_form.html.erb
<%= form_with(model: @vote, local: true) do |form| %>
    <div class="form-group">
    <% if @vote.errors.any? %>
        <div id="error_explanation">
            <h2><%= pluralize(@vote.errors.count, "error") %>Failure to save:</h2>

            <ul>
            <% @vote.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
            </ul>
        </div>
    <% end %>
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title, class: "form-control" %>
        </div>

        <div class="field">
            <%= form.label :deadline %>
            <%= form.datetime_field :deadline, class: "form-control" %>
        </div>

        <div class="actions">
            <%= form.submit class: "btn btn-primary" %>
        </div>
    </div>
<% end %>
<%= link_to "Back", votes_path %>

app/views/votes/edit.html.erb
<h1>Poll#: <%= @vote.id %> | <%= @vote.title %></h1>
<div class='row'>
    <%= render 'form' %>
</div>
<div class="row">
    <%= link_to 'back', vote_path(@vote), class: 'btn btn-light' %>
</div>

app/views/votes/index.html.erb
<% provide(:title, 'Votes') %>
<h1>Votes</h1>
<div class="container">
    <ul>
        <% @votes.each do |v| %>
        <li><%= link_to v.title, v %><br><%= v.deadline %></li>
        <% end %>
    </ul>
</div>

app/views/votes/new.html.erb
<h1>New Vote</h1>
<div class='row'>
    <%= render 'form' %>
</div>

app/views/votes/show.html.erb
<% provide(:title, @vote.title) %>
<h1>Poll#: <%= @vote.id %> | <%= @vote.title %></h1>
<div class="row">
    This vote will close at <%= @vote.deadline %>
</div>
<div class="row">
    <%= link_to 'Edit', edit_vote_path, class: 'btn btn-primary' %>
    <%= link_to 'back', votes_path, class: 'btn btn-light' %>
</div>